[package]
name = "host_sw"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = "0.8.1"
embedded-graphics-simulator = { git = "https://github.com/Kezii/simulator.git"}
rquansheng = {path = "../cross/rquansheng"}
