name: Build
on:
  merge_group:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build the project according to the steps
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install rust nightly
        run: |
          rustup toolchain install nightly --profile minimal --component rust-src --component rustfmt --component llvm-tools-preview
          rustup override set nightly

      - name: Configure rust target
        run: |
          rustup target add thumbv6m-none-eabi

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cargo check
        run: |
          cargo check --workspace --lib --bins --examples
